[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:suricata]
command=/usr/bin/suricata -c /etc/suricata/suricata.yaml -i eth0
autostart=false
autorestart=true
stderr_logfile=/var/log/suricata/error.log
stdout_logfile=/var/log/suricata/output.log

[program:zeek]
command=/opt/zeek/bin/zeek -i eth0 /opt/zeek/share/zeek/site/local.zeek
autostart=false
autorestart=true
stderr_logfile=/var/log/zeek/error.log
stdout_logfile=/var/log/zeek/output.log
